# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 95123b8fb5ab6a98f13309bf465fca97ce0cfbc45da8af992dd0416d2843cc1789968407903a660ec6ce9a92245bc8ace3758357b638082aed2a6af20daa15e0

test:
  secret_key_base: 79fab7b704b2a2512650eaa97c19a6bbf9aaf48b8d3fe4986882270913c104195c063962c08a3f18548f742ca254bec4a2044ce39c440e4719d153f6e7e4f234

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
